<?php

/**
 * @file
 * Drupal UI Icons.
 */

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\ui_icons\IconDefinitionInterface;

/**
 * Implements hook_help().
 */
function ui_icons_help(string $route_name, RouteMatchInterface $route_match): ?string {
  switch ($route_name) {
    case 'help.page.ui_icons':
      $output = '<h2>' . new TranslatableMarkup('About') . '</h2>';
      $output .= '<p>' . new TranslatableMarkup('UI Icons is a module that aims to simplify the front-end management of icons. For more information, see the <a href=":docs">online documentation for the UI Icons module</a>.', [
        ':docs' => 'https://www.drupal.org/docs/develop/theming-drupal/using-ui-icons',
      ]) . '</p>';
      $output .= '<dl>';
      $output .= '<dt>' . new TranslatableMarkup('General') . '</dt>';
      $output .= '<dd>' . new TranslatableMarkup('<a href=":docs">UI Icons</a> allow the declaration of icons in a Yaml file to be used globally on your website. The format allow to integrate many source provider for your icons and expose them in all Drupal display tools..', [
        ':docs' => 'https://www.drupal.org/docs/develop/theming-drupal/using-ui-icons',
      ]) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function ui_icons_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'input__icon' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for input icon template.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *
 * @see src/Element/UiIconAutocomplete.php
 */
function template_preprocess_input__icon(array &$variables): void {
  $variables['has_settings'] = $variables['element']['#show_settings'];
  $variables['icon_form'] = $variables['element']['icon_id'];

  if (isset($variables['element']['#default_value'])) {
    [$iconset_id, $icon_id] = explode(':', $variables['element']['#default_value']);
    $variables['iconset_id'] = $iconset_id;
    $variables['icon_id'] = $icon_id;
  }
  elseif (isset($variables['element']['#value']['object']) && $variables['element']['#value']['object'] instanceof IconDefinitionInterface) {
    $variables['iconset_id'] = $variables['element']['#value']['object']->getIconsetId();
    $variables['icon_id'] = $variables['element']['#value']['object']->getId();
  }

  if (isset($variables['element']['icon_settings'])) {
    $variables['settings_form'] = $variables['element']['icon_settings'];
  }
  elseif (isset($variables['element']['#default_settings'])) {
    $variables['settings_form'] = $variables['element']['#default_settings'];
  }

}
