<?php

/**
 * @file
 * Module implementation file.
 */

@class_alias('Drupal\ui_icons_backport\Attribute\IconExtractor', 'Drupal\Core\Theme\Icon\Attribute\IconExtractor');

@class_alias('Drupal\ui_icons_backport\Element\Icon', 'Drupal/Core/Render/Element/Icon');

@class_alias('Drupal\ui_icons_backport\Exception\IconDefinitionInvalidDataException', 'Drupal\Core\Theme\Icon\Exception\IconDefinitionInvalidDataException');
@class_alias('Drupal\ui_icons_backport\Exception\IconPackConfigErrorException', 'Drupal\Core\Theme\Icon\Exception\IconPackConfigErrorException');

@class_alias('Drupal\ui_icons_backport\IconDefinition', 'Drupal\Core\Theme\Icon\IconDefinition');
@class_alias('Drupal\ui_icons_backport\IconDefinitionInterface', 'Drupal\Core\Theme\Icon\IconDefinitionInterface');
@class_alias('Drupal\ui_icons_backport\IconExtractorBase', 'Drupal\Core\Theme\Icon\IconExtractorBase');
@class_alias('Drupal\ui_icons_backport\IconExtractorInterface', 'Drupal\Core\Theme\Icon\IconExtractorInterface');
@class_alias('Drupal\ui_icons_backport\IconExtractorPluginManager', 'Drupal\Core\Theme\Icon\IconExtractorPluginManager');
@class_alias('Drupal\ui_icons_backport\IconExtractorSettingsForm', 'Drupal\Core\Theme\Icon\IconExtractorSettingsForm');
@class_alias('Drupal\ui_icons_backport\IconExtractorWithFinder', 'Drupal\Core\Theme\Icon\IconExtractorWithFinder');
@class_alias('Drupal\ui_icons_backport\IconExtractorWithFinderInterface', 'Drupal\Core\Theme\Icon\IconExtractorWithFinderInterface');
@class_alias('Drupal\ui_icons_backport\IconFinder', 'Drupal\Core\Theme\Icon\IconFinder');
@class_alias('Drupal\ui_icons_backport\IconFinderInterface', 'Drupal\Core\Theme\Icon\IconFinderInterface');
@class_alias('Drupal\ui_icons_backport\IconPackExtractorForm', 'Drupal\Core\Theme\Icon\IconPackExtractorForm');

@class_alias('Drupal\ui_icons_backport\Plugin\IconPackManager', 'Drupal\Core\Theme\Icon\Plugin\IconPackManager');
@class_alias('Drupal\ui_icons_backport\Plugin\IconPackManagerInterface', 'Drupal\Core\Theme\Icon\Plugin\IconPackManagerInterface');

@class_alias('Drupal\ui_icons_backport\Template\IconsTwigExtension', 'Drupal\Core\Theme\Icon\Template\IconsTwigExtension');

@class_alias('Drupal\ui_icons_backport\IconCollector', 'Drupal\Core\Theme\Icon\IconCollector');
