<?php

/**
 * @file
 * Drupal hooks and global functions for ui_icons_menu module.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Theme\Icon\IconDefinition;

/**
 * Implements hook_help().
 */
function ui_icons_menu_help(string $route_name, RouteMatchInterface $route_match) {
  if ('help.page.ui_icons_menu' === $route_name) {
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The UI Icons Menu module overtakes the core default widget for menu link content entities, allowing you to set icons on menu links.') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 *
 * @todo set settings options, position and required as menu setting or global
 * for all menus.
 */
function ui_icons_menu_entity_base_field_info_alter(array &$fields, EntityTypeInterface $entity_type): void {
  if ($entity_type->id() === 'menu_link_content') {
    $moduleDiscovery = \Drupal::service('module_handler');
    $type = 'icon_link_widget';
    if ($moduleDiscovery->moduleExists('ui_icons_field_link_attributes')) {
      $type = 'icon_link_attributes_widget';
    }
    $fields['link']->setDisplayOptions('form', [
      'type' => $type,
      // Allow icon position and settings.
      'settings' => [
        'icon_position' => TRUE,
        'show_settings' => TRUE,
      ],
    ]);
    // Icon is always optional for now.
    $fields['link']->setRequired(FALSE);
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function ui_icons_menu_preprocess_menu(array &$variables): void {
  if (empty($variables['items'])) {
    return;
  }
  ui_icons_menu__preprocess_menu($variables['items']);
}

/**
 * Handle menu items to add our icon.
 *
 * @param array $items
 *   The menu items.
 */
function ui_icons_menu__preprocess_menu(array &$items): void {
  foreach ($items as &$item) {
    if (empty($item['url'])) {
      continue;
    }

    ui_icons_menu__preprocess_menu_item($item);

    if (!empty($item['below'])) {
      ui_icons_menu__preprocess_menu($item['below']);
    }
  }
}

/**
 * Handle a single menu item.
 *
 * @param array $item
 *   The menu item.
 */
function ui_icons_menu__preprocess_menu_item(array &$item): void {
  /** @var \Drupal\Core\Url $url */
  $url = $item['url'];

  $options = $url->getOptions();
  if (!isset($options['icon']['target_id']) || !empty($options['already_processed'])) {
    return;
  }

  $icon_full_id = $options['icon']['target_id'];
  if (FALSE === strpos($icon_full_id, IconDefinition::ICON_SEPARATOR)) {
    return;
  }

  /** @var \Drupal\Core\Theme\Icon\Plugin\IconPackManagerInterface $pluginManagerIconPack */
  $pluginManagerIconPack = \Drupal::service('plugin.manager.icon_pack');
  $icon = $pluginManagerIconPack->getIcon($icon_full_id);

  if (NULL === $icon) {
    return;
  }

  $icon_settings = [];
  if (isset($options['icon']['settings'][$icon->getPackId()])) {
    $icon_settings = $options['icon']['settings'][$icon->getPackId()];
  }
  $icon_renderable = $icon->getRenderable($icon_settings);
  $icon = \Drupal::service('renderer')->renderInIsolation($icon_renderable);

  $icon_display = $options['icon_display'] ?? 'before';
  switch ($icon_display) {
    case 'before':
      $item['title'] = new FormattableMarkup('@icon<span class="i-icons-menu-text">@title</span>', [
        '@title' => $item['title'],
        '@icon' => $icon,
      ]);
      break;

    case 'after':
      $item['title'] = new FormattableMarkup('<span class="i-icons-menu-text">@title</span>@icon', [
        '@title' => $item['title'],
        '@icon' => $icon,
      ]);
      break;

    default:
      $item['title'] = new FormattableMarkup('@icon', [
        '@icon' => $icon,
      ]);
      break;
  }
  // print("\n");
  // print_r($icon);
  // print("\n");
  // print_r($item['title']);
  // print("\n");
}
